---
# global user config:
user: lilian
accounts: 
  - lilian
users:
  lilian:
    - l3d@pinkie.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@business.wingcon.com
    - l3d@derpy.l3d.yt
    - l3d@mobile.l3d.yt 

admins:
  - lilian

admins_ssh_root_prefix: 
  - l3d

ssh_public_key_store: 'admin_ssh_keys' 

home_sweet_home: false

install_keychain: true
# i3wm config:

i3_packages_extra:
  - ranger
  - light
  - pass
  - gnome
  - asciinema
  - mtr
  - evince
  - libreoffice
  - speedtest-cli
  - htop
  - dunst
  - keychain
  - python-pip

i3_keybindings_extra:
  - keybinding:
    name: Volume (mute/unmute)
    key: $mod+F12
    exec: --no-startup-id pulsemixer --toggle-mute
  - keybinding:
    name: Volue (default)
    key: $mod+Shift+F12
    exec: --no-startup-id pulsemixer --set-volume 42
  - keybinding:
    name: volume-up
    key: XF86AudioRaiseVolume
    exec: --no-startup-id pulsemixer --change-volume +4
  - keybinding:
    name: volume-down
    key: XF86AudioLowerVolume
    exec: --no-startup-id pulsemixer --change-volume -5
  - keybinding:
    name: darker
    key: XF86AudioMute
    exec: --no-startup-id pulsemixer --toggle-mute 
  - keybinding:
    name: darker
    key: XF86MonBrightnessDown
    exec: --no-startup-id light -U 12
  - keybinding:
    name: lighter
    key: XF86MonBrightnessUp
    exec: --no-startup-id light -A 9


i3_applications:
  - application:
    class: "Firefox"
    name: "firefox"
    workspace: 2
    on_startup: true
  - application:
    class: "Thunderbird"
    name: "thunderbird"
    workspace: 9
    on_startup: true
  - application:
    class: "Evolution"
    name: "evolution"
    workspace: 9
    on_startup: false


i3_run_on_startup:
  - xrandr --output HDMI2 --mode 1920x1200 --auto --right-of DP1 --output DP1 --mode 2560x1440 --auto
  - sudo nm-applet
  - nextcloud

i3:
  font_size: 12
  focus_follows_mouse: true

i3_desktop_env:
  background: "/home/{{ user }}/.config/background.png"

i3lock_options: "i3lock --image=/home/{{ user }}/.config/lockscreen.png --color 000000"

extra_bashrc: alias wingcon_vpn="sudo openvpn --config /home/lilian/.vpn/stark-TCP-443-lilian/stark-TCP-443-lilian.ovpn"

