---

- name: Install useful packages
  hosts: thinkpad
  tags: 
  - packages
  - updates
  - setup
  roles:
    - workstation_packages

- name: Install useful dotfiles
  hosts: thinkpad
  tags: 
  - setup
  roles:
    - dotfiles

- name: install modules for sound and bluetooth
  hosts: thinkpad
  tags:
  - setup
  - pulseaudio
  roles:
    - pulseaudio

# - name: improve firefox configuration
#  hosts: thinkpad
#  tags:
#  - setup
#  - firefox
#  roles:
#    - firefox

- name: Install useful packages
  hosts: thinkpad
  tags: 
  - packages
  - i3wm
  roles:
    - copy_files
    - i3wm


