---

- name: copy files
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'files/background.png', dest: "/home/{{ user }}/.config/background.png" }
    - { src: 'files/lockscreen.png', dest: '/home/{{ user }}/.config/lockscreen.png' }
    - { src: 'files/xinitrc', dest: '/home/{{ user }}/.xinitrc' }

