---

- name: copy bg
  copy:
    src: files/background.png
    dest: /home/{{ user }}/.config/background.png
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: copy bg
  copy:
    src: files/lockscreen.png
    dest: /home/{{ user }}/.config/lockscreen.png
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: copy start
  copy:
    src: files/start.sh
    dest: /opt/start.sh
    owner: "root"
    group: "root"
    mode: 0644

